// part14-jest_react/src/containers/TodoList/TodoList.js
import React, { Component } from "react";
import Header from "./components/Header";
import UndoList from "./components/UndoList";
import './index.css';

class TodoList extends Component {
    state = {
        undoList : []
    }
    addUndoItem = (value) => { 
        this.setState({
            undoList: [...this.state.undoList, value]
        })
    }
    deleteItem = (index) => { 
        const newList = [...this.state.undoList];
        newList.splice(index, 1);
        this.setState({
            undoList:newList
        })
    }
    render() {
        const { undoList } = this.state;
        return (
            <>
                <Header addUndoItem={this.addUndoItem} />
                <UndoList list={undoList} deleteItem={this.deleteItem}/>
            </>
        )

    }
}
export default TodoList;

// part13-jest_vue/src/containers/TodoList/TodoList.vue
<template>
	<div class>
		<Header @add="addUndoItem" />
		<UndoList :list="undoList" @delete="handleDeleteItem" />
	</div>
</template>

<script>
import Header from './components/Header';
import UndoList from './components/UndoList';

export default {
	name: 'TodoList',
	components: {
		Header,
		UndoList
	},
	data() {
		return {
			undoList: []
		};
	},
	methods: {
		addUndoItem(inputValue) {
			this.undoList.push({
				status: 'div',
				value: inputValue
			});
		},
		handleDeleteItem(index) {
			this.undoList.splice(index, 1);
		}
	}
};
</script>

<style lang="stylus"></style>
